import { beforeEach, describe, expect, it, vi } from "vitest"
import { MAX_IMAGE_BYTES } from "@/lib/image-file"

const USER = "user-1"
const PNG = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0])

type StoredObject = { body: Uint8Array; contentType?: string }

/** Stands in for the R2 binding with an in-memory map. */
function createFakeR2() {
  const objects = new Map<string, StoredObject>()
  return {
    objects,
    put: vi.fn(
      async (
        key: string,
        value: ArrayBuffer | Uint8Array,
        options?: { httpMetadata?: { contentType?: string } },
      ) => {
        objects.set(key, {
          body: new Uint8Array(value),
          contentType: options?.httpMetadata?.contentType,
        })
        return { key }
      },
    ),
    get: vi.fn(async (key: string) => {
      const object = objects.get(key)
      if (!object) return null
      return {
        body: new Blob([object.body]).stream(),
        size: object.body.byteLength,
        httpEtag: `"${key}"`,
        httpMetadata: { contentType: object.contentType },
      }
    }),
  }
}

const mocks = vi.hoisted(() => ({
  session: null as { user: { id: string } } | null,
  bucket: null as unknown,
}))

vi.mock("@opennextjs/cloudflare", () => ({
  getCloudflareContext: async () => ({ env: { IMAGES: mocks.bucket } }),
}))
vi.mock("@/auth/server", () => ({
  getSession: async () => mocks.session,
}))

const { POST } = await import("./route")
const { GET } = await import("./[userId]/[file]/route")

let bucket: ReturnType<typeof createFakeR2>

beforeEach(() => {
  bucket = createFakeR2()
  mocks.bucket = bucket
  mocks.session = { user: { id: USER } }
})

function upload(file?: Blob, name = "pasted.png") {
  const form = new FormData()
  if (file) form.set("file", file, name)
  return POST(
    new Request("http://localhost/api/images", { method: "POST", body: form }),
  )
}

function download(userId: string, file: string) {
  return GET(new Request(`http://localhost/api/images/${userId}/${file}`), {
    params: Promise.resolve({ userId, file }),
  })
}

describe("POST /api/images", () => {
  it("rejects a signed-out request without storing anything", async () => {
    mocks.session = null

    const response = await upload(new Blob([PNG], { type: "image/png" }))

    expect(response.status).toBe(401)
    expect(bucket.put).not.toHaveBeenCalled()
  })

  it("rejects a request without a file", async () => {
    const response = await upload()

    expect(response.status).toBe(400)
    expect(bucket.put).not.toHaveBeenCalled()
  })

  it("rejects a file over the size limit", async () => {
    const oversized = new Uint8Array(MAX_IMAGE_BYTES + 1)
    oversized.set(PNG)

    const response = await upload(new Blob([oversized], { type: "image/png" }))

    expect(response.status).toBe(413)
    expect(bucket.put).not.toHaveBeenCalled()
  })

  it("rejects content that is not a supported image even if labelled as one", async () => {
    const svg = new TextEncoder().encode("<svg onload=alert(1)></svg>")

    const response = await upload(new Blob([svg], { type: "image/png" }))

    expect(response.status).toBe(415)
    expect(bucket.put).not.toHaveBeenCalled()
  })

  it("stores the image under the user's prefix and returns its URL", async () => {
    const response = await upload(
      new Blob([PNG], { type: "application/octet-stream" }),
    )

    expect(response.status).toBe(201)
    const { url } = (await response.json()) as { url: string }
    expect(url).toMatch(
      new RegExp(`^/api/images/${USER}/[0-9a-f-]{36}\\.png$`),
    )

    const key = url.replace("/api/images/", "")
    const stored = bucket.objects.get(key)
    expect(stored?.contentType).toBe("image/png")
    expect(stored?.body).toEqual(PNG)
  })
})

describe("GET /api/images/[userId]/[file]", () => {
  it("returns 404 for a name that was not generated by the upload", async () => {
    const response = await download(USER, "index.html")

    expect(response.status).toBe(404)
    expect(bucket.get).not.toHaveBeenCalled()
  })

  it("returns 404 when the image does not exist", async () => {
    const response = await download(
      USER,
      "0f8fad5b-d9cb-469f-a165-70867728950e.png",
    )

    expect(response.status).toBe(404)
  })

  it("serves an uploaded image with its type and long-lived caching", async () => {
    const uploaded = await upload(new Blob([PNG], { type: "image/png" }))
    const { url } = (await uploaded.json()) as { url: string }
    const [userId, file] = url.replace("/api/images/", "").split("/")

    const response = await download(userId, file)

    expect(response.status).toBe(200)
    expect(response.headers.get("content-type")).toBe("image/png")
    expect(response.headers.get("x-content-type-options")).toBe("nosniff")
    expect(response.headers.get("cache-control")).toContain("immutable")
    expect(new Uint8Array(await response.arrayBuffer())).toEqual(PNG)
  })
})
